server:
  port: 8081

spring:
  application:
    name: pstest
  datasource:
    url: jdbc:mysql://localhost:3306/courseware
    username: root
    password: lzhlzh594594
    driver-class-name: com.mysql.cj.jdbc.Driver




